class MuseumExecutor {
    public static void main(String[] instruments) {
        Museum museum1 = new Museum();
        museum1.museumId = 1;
        museum1.museumName = "Gem Museum, New York";
        museum1.location = "New York, USA";
        museum1.totalDiamonds = 50;
        Diamond diamond1 = new Diamond();
        diamond1.diamondId = 101;
        diamond1.diamondName = "Hope Diamond";
        diamond1.diamondOrigin = "India";
        museum1.diamond = diamond1;
        museum1.displayMuseumInfo();

        Museum museum2 = new Museum();
        museum2.museumId = 2;
        museum2.museumName = "London Diamond Museum";
        museum2.location = "London, UK";
        museum2.totalDiamonds = 45;
        Diamond diamond2 = new Diamond();
        diamond2.diamondId = 102;
        diamond2.diamondName = "Koh-i-Noor";
        diamond2.diamondOrigin = "India";
        museum2.diamond = diamond2;
        museum2.displayMuseumInfo();

        Museum museum3 = new Museum();
        museum3.museumId = 3;
        museum3.museumName = "Paris Gem Museum";
        museum3.location = "Paris, France";
        museum3.totalDiamonds = 40;
        Diamond diamond3 = new Diamond();
        diamond3.diamondId = 103;
        diamond3.diamondName = "Regent Diamond";
        diamond3.diamondOrigin = "India";
        museum3.diamond = diamond3;
        museum3.displayMuseumInfo();

        Museum museum4 = new Museum();
        museum4.museumId = 4;
        museum4.museumName = "Amsterdam Diamond Museum";
        museum4.location = "Amsterdam, Netherlands";
        museum4.totalDiamonds = 35;
        Diamond diamond4 = new Diamond();
        diamond4.diamondId = 104;
        diamond4.diamondName = "Cullinan Diamond";
        diamond4.diamondOrigin = "South Africa";
        museum4.diamond = diamond4;
        museum4.displayMuseumInfo();

        Museum museum5 = new Museum();
        museum5.museumId = 5;
        museum5.museumName = "Moscow Diamond Fund";
        museum5.location = "Moscow, Russia";
        museum5.totalDiamonds = 60;
        Diamond diamond5 = new Diamond();
        diamond5.diamondId = 105;
        diamond5.diamondName = "Orlov Diamond";
        diamond5.diamondOrigin = "India";
        museum5.diamond = diamond5;
        museum5.displayMuseumInfo();

        Museum museum6 = new Museum();
        museum6.museumId = 6;
        museum6.museumName = "Dubai Gem Museum";
        museum6.location = "Dubai, UAE";
        museum6.totalDiamonds = 55;
        Diamond diamond6 = new Diamond();
        diamond6.diamondId = 106;
        diamond6.diamondName = "Sancy Diamond";
        diamond6.diamondOrigin = "India";
        museum6.diamond = diamond6;
        museum6.displayMuseumInfo();

        Museum museum7 = new Museum();
        museum7.museumId = 7;
        museum7.museumName = "Toronto Diamond Museum";
        museum7.location = "Toronto, Canada";
        museum7.totalDiamonds = 48;
        Diamond diamond7 = new Diamond();
        diamond7.diamondId = 107;
        diamond7.diamondName = "Dresden Green";
        diamond7.diamondOrigin = "India";
        museum7.diamond = diamond7;
        museum7.displayMuseumInfo();

        Museum museum8 = new Museum();
        museum8.museumId = 8;
        museum8.museumName = "Tokyo Gem Museum";
        museum8.location = "Tokyo, Japan";
        museum8.totalDiamonds = 42;
        Diamond diamond8 = new Diamond();
        diamond8.diamondId = 108;
        diamond8.diamondName = "Koh-i-Tan";
        diamond8.diamondOrigin = "India";
        museum8.diamond = diamond8;
        museum8.displayMuseumInfo();

        Museum museum9 = new Museum();
        museum9.museumId = 9;
        museum9.museumName = "Berlin Diamond Museum";
        museum9.location = "Berlin, Germany";
        museum9.totalDiamonds = 38;
        Diamond diamond9 = new Diamond();
        diamond9.diamondId = 109;
        diamond9.diamondName = "Tiffany Diamond";
        diamond9.diamondOrigin = "South Africa";
        museum9.diamond = diamond9;
        museum9.displayMuseumInfo();

        Museum museum10 = new Museum();
        museum10.museumId = 10;
        museum10.museumName = "Bangkok Gem Museum";
        museum10.location = "Bangkok, Thailand";
        museum10.totalDiamonds = 44;
        Diamond diamond10 = new Diamond();
        diamond10.diamondId = 110;
        diamond10.diamondName = "Blue Heart";
        diamond10.diamondOrigin = "South Africa";
        museum10.diamond = diamond10;
        museum10.displayMuseumInfo();

        Museum museum11 = new Museum();
        museum11.museumId = 11;
        museum11.museumName = "New York Gem Museum-2";
        museum11.location = "New York, USA";
        museum11.totalDiamonds = 50;
        Diamond diamond11 = new Diamond();
        diamond11.diamondId = 111;
        diamond11.diamondName = "Regent II";
        diamond11.diamondOrigin = "India";
        museum11.diamond = diamond11;
        museum11.displayMuseumInfo();

        Museum museum12 = new Museum();
        museum12.museumId = 12;
        museum12.museumName = "London Diamond Museum-2";
        museum12.location = "London, UK";
        museum12.totalDiamonds = 45;
        Diamond diamond12 = new Diamond();
        diamond12.diamondId = 112;
        diamond12.diamondName = "Koh-i-Noor II";
        diamond12.diamondOrigin = "India";
        museum12.diamond = diamond12;
        museum12.displayMuseumInfo();

        Museum museum13 = new Museum();
        museum13.museumId = 13;
        museum13.museumName = "Paris Gem Museum-2";
        museum13.location = "Paris, France";
        museum13.totalDiamonds = 40;
        Diamond diamond13 = new Diamond();
        diamond13.diamondId = 113;
        diamond13.diamondName = "Regent III";
        diamond13.diamondOrigin = "India";
        museum13.diamond = diamond13;
        museum13.displayMuseumInfo();

        Museum museum14 = new Museum();
        museum14.museumId = 14;
        museum14.museumName = "Amsterdam Diamond Museum-2";
        museum14.location = "Amsterdam, Netherlands";
        museum14.totalDiamonds = 35;
        Diamond diamond14 = new Diamond();
        diamond14.diamondId = 114;
        diamond14.diamondName = "Cullinan II";
        diamond14.diamondOrigin = "South Africa";
        museum14.diamond = diamond14;
        museum14.displayMuseumInfo();

        Museum museum15 = new Museum();
        museum15.museumId = 15;
        museum15.museumName = "Moscow Diamond Fund-2";
        museum15.location = "Moscow, Russia";
        museum15.totalDiamonds = 60;
        Diamond diamond15 = new Diamond();
        diamond15.diamondId = 115;
        diamond15.diamondName = "Orlov II";
        diamond15.diamondOrigin = "India";
        museum15.diamond = diamond15;
        museum15.displayMuseumInfo();

        Museum museum16 = new Museum();
        museum16.museumId = 16;
        museum16.museumName = "Dubai Gem Museum-2";
        museum16.location = "Dubai, UAE";
        museum16.totalDiamonds = 55;
        Diamond diamond16 = new Diamond();
        diamond16.diamondId = 116;
        diamond16.diamondName = "Sancy II";
        diamond16.diamondOrigin = "India";
        museum16.diamond = diamond16;
        museum16.displayMuseumInfo();

        Museum museum17 = new Museum();
        museum17.museumId = 17;
        museum17.museumName = "Toronto Diamond Museum-2";
        museum17.location = "Toronto, Canada";
        museum17.totalDiamonds = 48;
        Diamond diamond17 = new Diamond();
        diamond17.diamondId = 117;
        diamond17.diamondName = "Dresden II";
        diamond17.diamondOrigin = "India";
        museum17.diamond = diamond17;
        museum17.displayMuseumInfo();

        Museum museum18 = new Museum();
        museum18.museumId = 18;
        museum18.museumName = "Tokyo Gem Museum-2";
        museum18.location = "Tokyo, Japan";
        museum18.totalDiamonds = 42;
        Diamond diamond18 = new Diamond();
        diamond18.diamondId = 118;
        diamond18.diamondName = "Koh-i-Tan II";
        diamond18.diamondOrigin = "India";
        museum18.diamond = diamond18;
        museum18.displayMuseumInfo();

        Museum museum19 = new Museum();
        museum19.museumId = 19;
        museum19.museumName = "Berlin Diamond Museum-2";
        museum19.location = "Berlin, Germany";
        museum19.totalDiamonds = 38;
        Diamond diamond19 = new Diamond();
        diamond19.diamondId = 119;
        diamond19.diamondName = "Tiffany II";
        diamond19.diamondOrigin = "South Africa";
        museum19.diamond = diamond19;
        museum19.displayMuseumInfo();

        Museum museum20 = new Museum();
        museum20.museumId = 20;
        museum20.museumName = "Bangkok Gem Museum-2";
        museum20.location = "Bangkok, Thailand";
        museum20.totalDiamonds = 44;
        Diamond diamond20 = new Diamond();
        diamond20.diamondId = 120;
        diamond20.diamondName = "Blue Heart II";
        diamond20.diamondOrigin = "South Africa";
        museum20.diamond = diamond20;
        museum20.displayMuseumInfo();
    }
}