class ShoeLaceExecutor {

    public static void main(String[] shoe) {

        // ShoeLace 1
        ShoeLace shoeLace1 = new ShoeLace();
        shoeLace1.color = "Black";
        String color = shoeLace1.color;
        shoeLace1.length = 40;
        double length = shoeLace1.length;
        shoeLace1.material = "Cotton";
        String material = shoeLace1.material;
        shoeLace1.isFlat = true;
        boolean isFlat = shoeLace1.isFlat;
        shoeLace1.tipMaterial = "Plastic";
        String tipMaterial = shoeLace1.tipMaterial;
        shoeLace1.thickness = 5;
        int thickness = shoeLace1.thickness;
        shoeLace1.elastic = false;
        boolean elastic = shoeLace1.elastic;
        shoeLace1.brand = "Nike";
        String brand = shoeLace1.brand;
        shoeLace1.reflective = false;
        boolean reflective = shoeLace1.reflective;
        shoeLace1.pattern = "Solid";
		String pattern = shoeLace1.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 2
        ShoeLace shoeLace2 = new ShoeLace();
        shoeLace2.color = "White";
        color = shoeLace2.color;
        shoeLace2.length = 45;
        length = shoeLace2.length;
        shoeLace2.material = "Nylon";
        material = shoeLace2.material;
        shoeLace2.isFlat = false;
        isFlat = shoeLace2.isFlat;
        shoeLace2.tipMaterial = "Metal";
        tipMaterial = shoeLace2.tipMaterial;
        shoeLace2.thickness = 4;
        thickness = shoeLace2.thickness;
        shoeLace2.elastic = true;
        elastic = shoeLace2.elastic;
        shoeLace2.brand = "Adidas";
        brand = shoeLace2.brand;
        shoeLace2.reflective = true;
        reflective = shoeLace2.reflective;
        shoeLace2.pattern = "Striped";
		 pattern = shoeLace2.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 3
        ShoeLace shoeLace3 = new ShoeLace();
        shoeLace3.color = "Red";
        color = shoeLace3.color;
        shoeLace3.length = 50;
        length = shoeLace3.length;
        shoeLace3.material = "Leather";
        material = shoeLace3.material;
        shoeLace3.isFlat = true;
        isFlat = shoeLace3.isFlat;
        shoeLace3.tipMaterial = "Plastic";
        tipMaterial = shoeLace3.tipMaterial;
        shoeLace3.thickness = 6;
        thickness = shoeLace3.thickness;
        shoeLace3.elastic = false;
        elastic = shoeLace3.elastic;
        shoeLace3.brand = "Puma";
        brand = shoeLace3.brand;
        shoeLace3.reflective = false;
        reflective = shoeLace3.reflective;
        shoeLace3.pattern = "Dotted";
		pattern = shoeLace3.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 4
        ShoeLace shoeLace4 = new ShoeLace();
        shoeLace4.color = "Blue";
        color = shoeLace4.color;
        shoeLace4.length = 35;
        length = shoeLace4.length;
        shoeLace4.material = "Cotton";
        material = shoeLace4.material;
        shoeLace4.isFlat = false;
        isFlat = shoeLace4.isFlat;
        shoeLace4.tipMaterial = "Metal";
        tipMaterial = shoeLace4.tipMaterial;
        shoeLace4.thickness = 5;
        thickness = shoeLace4.thickness;
        shoeLace4.elastic = true;
        elastic = shoeLace4.elastic;
        shoeLace4.brand = "Reebok";
        brand = shoeLace4.brand;
        shoeLace4.reflective = true;
        reflective = shoeLace4.reflective;
        shoeLace4.pattern = "Solid";
		pattern = shoeLace4.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 5
        ShoeLace shoeLace5 = new ShoeLace();
        shoeLace5.color = "Green";
        color = shoeLace5.color;
        shoeLace5.length = 42;
        length = shoeLace5.length;
        shoeLace5.material = "Nylon";
        material = shoeLace5.material;
        shoeLace5.isFlat = true;
        isFlat = shoeLace5.isFlat;
        shoeLace5.tipMaterial = "Plastic";
        tipMaterial = shoeLace5.tipMaterial;
        shoeLace5.thickness = 4;
        thickness = shoeLace5.thickness;
        shoeLace5.elastic = false;
        elastic = shoeLace5.elastic;
        shoeLace5.brand = "Skechers";
        brand = shoeLace5.brand;
        shoeLace5.reflective = false;
        reflective = shoeLace5.reflective;
        shoeLace5.pattern = "Striped";
		pattern = shoeLace5.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 6
        ShoeLace shoeLace6 = new ShoeLace();
        shoeLace6.color = "Yellow";
        color = shoeLace6.color;
        shoeLace6.length = 38;
        length = shoeLace6.length;
        shoeLace6.material = "Leather";
        material = shoeLace6.material;
        shoeLace6.isFlat = false;
        isFlat = shoeLace6.isFlat;
        shoeLace6.tipMaterial = "Metal";
        tipMaterial = shoeLace6.tipMaterial;
        shoeLace6.thickness = 6;
        thickness = shoeLace6.thickness;
        shoeLace6.elastic = true;
        elastic = shoeLace6.elastic;
        shoeLace6.brand = "Converse";
        brand = shoeLace6.brand;
        shoeLace6.reflective = true;
        reflective = shoeLace6.reflective;
        shoeLace6.pattern = "Dotted";
		pattern = shoeLace6.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 7
        ShoeLace shoeLace7 = new ShoeLace();
        shoeLace7.color = "Orange";
        color = shoeLace7.color;
        shoeLace7.length = 44;
        length = shoeLace7.length;
        shoeLace7.material = "Cotton";
        material = shoeLace7.material;
        shoeLace7.isFlat = true;
        isFlat = shoeLace7.isFlat;
        shoeLace7.tipMaterial = "Plastic";
        tipMaterial = shoeLace7.tipMaterial;
        shoeLace7.thickness = 5;
        thickness = shoeLace7.thickness;
        shoeLace7.elastic = false;
        elastic = shoeLace7.elastic;
        shoeLace7.brand = "Vans";
        brand = shoeLace7.brand;
        shoeLace7.reflective = false;
        reflective = shoeLace7.reflective;
        shoeLace7.pattern = "Solid";
		pattern = shoeLace7.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 8
        ShoeLace shoeLace8 = new ShoeLace();
        shoeLace8.color = "Purple";
        color = shoeLace8.color;
        shoeLace8.length = 39;
        length = shoeLace8.length;
        shoeLace8.material = "Nylon";
        material = shoeLace8.material;
        shoeLace8.isFlat = false;
        isFlat = shoeLace8.isFlat;
        shoeLace8.tipMaterial = "Metal";
        tipMaterial = shoeLace8.tipMaterial;
        shoeLace8.thickness = 4;
        thickness = shoeLace8.thickness;
        shoeLace8.elastic = true;
        elastic = shoeLace8.elastic;
        shoeLace8.brand = "New Balance";
        brand = shoeLace8.brand;
        shoeLace8.reflective = true;
        reflective = shoeLace8.reflective;
        shoeLace8.pattern = "Striped";
		pattern = shoeLace8.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 9
        ShoeLace shoeLace9 = new ShoeLace();
        shoeLace9.color = "Grey";
        color = shoeLace9.color;
        shoeLace9.length = 41;
        length = shoeLace9.length;
        shoeLace9.material = "Leather";
        material = shoeLace9.material;
        shoeLace9.isFlat = true;
        isFlat = shoeLace9.isFlat;
        shoeLace9.tipMaterial = "Plastic";
        tipMaterial = shoeLace9.tipMaterial;
        shoeLace9.thickness = 5;
        thickness = shoeLace9.thickness;
        shoeLace9.elastic = false;
        elastic = shoeLace9.elastic;
        shoeLace9.brand = "Fila";
        brand = shoeLace9.brand;
        shoeLace9.reflective = false;
        reflective = shoeLace9.reflective;
        shoeLace9.pattern = "Dotted";
		pattern = shoeLace9.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);
		
		        // ShoeLace 10
        ShoeLace shoeLace10 = new ShoeLace();
        shoeLace10.color = "Pink";
        color = shoeLace10.color;
        shoeLace10.length = 36;
        length = shoeLace10.length;
        shoeLace10.material = "Cotton";
        material = shoeLace10.material;
        shoeLace10.isFlat = false;
        isFlat = shoeLace10.isFlat;
        shoeLace10.tipMaterial = "Metal";
        tipMaterial = shoeLace10.tipMaterial;
        shoeLace10.thickness = 4;
        thickness = shoeLace10.thickness;
        shoeLace10.elastic = true;
        elastic = shoeLace10.elastic;
        shoeLace10.brand = "Asics";
        brand = shoeLace10.brand;
        shoeLace10.reflective = true;
        reflective = shoeLace10.reflective;
        shoeLace10.pattern = "Solid";
		pattern = shoeLace10.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 11
        ShoeLace shoeLace11 = new ShoeLace();
        shoeLace11.color = "Dark Blue";
        color = shoeLace11.color;
        shoeLace11.length = 43;
        length = shoeLace11.length;
        shoeLace11.material = "Nylon";
        material = shoeLace11.material;
        shoeLace11.isFlat = true;
        isFlat = shoeLace11.isFlat;
        shoeLace11.tipMaterial = "Plastic";
        tipMaterial = shoeLace11.tipMaterial;
        shoeLace11.thickness = 5;
        thickness = shoeLace11.thickness;
        shoeLace11.elastic = false;
        elastic = shoeLace11.elastic;
        shoeLace11.brand = "Mizuno";
        brand = shoeLace11.brand;
        shoeLace11.reflective = false;
        reflective = shoeLace11.reflective;
        shoeLace11.pattern = "Striped";
		pattern = shoeLace11.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 12
        ShoeLace shoeLace12 = new ShoeLace();
        shoeLace12.color = "Light Green";
        color = shoeLace12.color;
        shoeLace12.length = 37;
        length = shoeLace12.length;
        shoeLace12.material = "Leather";
        material = shoeLace12.material;
        shoeLace12.isFlat = false;
        isFlat = shoeLace12.isFlat;
        shoeLace12.tipMaterial = "Metal";
        tipMaterial = shoeLace12.tipMaterial;
        shoeLace12.thickness = 6;
        thickness = shoeLace12.thickness;
        shoeLace12.elastic = true;
        elastic = shoeLace12.elastic;
        shoeLace12.brand = "Brooks";
        brand = shoeLace12.brand;
        shoeLace12.reflective = true;
        reflective = shoeLace12.reflective;
        shoeLace12.pattern = "Dotted";
		pattern = shoeLace12.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 13
        ShoeLace shoeLace13 = new ShoeLace();
        shoeLace13.color = "Beige";
        color = shoeLace13.color;
        shoeLace13.length = 46;
        length = shoeLace13.length;
        shoeLace13.material = "Cotton";
        material = shoeLace13.material;
        shoeLace13.isFlat = true;
        isFlat = shoeLace13.isFlat;
        shoeLace13.tipMaterial = "Plastic";
        tipMaterial = shoeLace13.tipMaterial;
        shoeLace13.thickness = 5;
        thickness = shoeLace13.thickness;
        shoeLace13.elastic = false;
        elastic = shoeLace13.elastic;
        shoeLace13.brand = "Under Armour";
        brand = shoeLace13.brand;
        shoeLace13.reflective = false;
        reflective = shoeLace13.reflective;
        shoeLace13.pattern = "Solid";
		pattern = shoeLace13.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 14
        ShoeLace shoeLace14 = new ShoeLace();
        shoeLace14.color = "Brown";
        color = shoeLace14.color;
        shoeLace14.length = 40;
        length = shoeLace14.length;
        shoeLace14.material = "Nylon";
        material = shoeLace14.material;
        shoeLace14.isFlat = false;
        isFlat = shoeLace14.isFlat;
        shoeLace14.tipMaterial = "Metal";
        tipMaterial = shoeLace14.tipMaterial;
        shoeLace14.thickness = 4;
        thickness = shoeLace14.thickness;
        shoeLace14.elastic = true;
        elastic = shoeLace14.elastic;
        shoeLace14.brand = "Diadora";
        brand = shoeLace14.brand;
        shoeLace14.reflective = true;
        reflective = shoeLace14.reflective;
        shoeLace14.pattern = "Striped";
		pattern = shoeLace14.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);
		
		        // ShoeLace 15
        ShoeLace shoeLace15 = new ShoeLace();
        shoeLace15.color = "Maroon";
        color = shoeLace15.color;
        shoeLace15.length = 42;
        length = shoeLace15.length;
        shoeLace15.material = "Leather";
        material = shoeLace15.material;
        shoeLace15.isFlat = true;
        isFlat = shoeLace15.isFlat;
        shoeLace15.tipMaterial = "Plastic";
        tipMaterial = shoeLace15.tipMaterial;
        shoeLace15.thickness = 5;
        thickness = shoeLace15.thickness;
        shoeLace15.elastic = false;
        elastic = shoeLace15.elastic;
        shoeLace15.brand = "Salomon";
        brand = shoeLace15.brand;
        shoeLace15.reflective = false;
        reflective = shoeLace15.reflective;
        shoeLace15.pattern = "Dotted";
		pattern = shoeLace15.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 16
        ShoeLace shoeLace16 = new ShoeLace();
        shoeLace16.color = "Cyan";
        color = shoeLace16.color;
        shoeLace16.length = 38;
        length = shoeLace16.length;
        shoeLace16.material = "Cotton";
        material = shoeLace16.material;
        shoeLace16.isFlat = false;
        isFlat = shoeLace16.isFlat;
        shoeLace16.tipMaterial = "Metal";
        tipMaterial = shoeLace16.tipMaterial;
        shoeLace16.thickness = 4;
        thickness = shoeLace16.thickness;
        shoeLace16.elastic = true;
        elastic = shoeLace16.elastic;
        shoeLace16.brand = "K-Swiss";
        brand = shoeLace16.brand;
        shoeLace16.reflective = true;
        reflective = shoeLace16.reflective;
        shoeLace16.pattern = "Solid";
		pattern = shoeLace16.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 17
        ShoeLace shoeLace17 = new ShoeLace();
        shoeLace17.color = "Magenta";
        color = shoeLace17.color;
        shoeLace17.length = 44;
        length = shoeLace17.length;
        shoeLace17.material = "Nylon";
        material = shoeLace17.material;
        shoeLace17.isFlat = true;
        isFlat = shoeLace17.isFlat;
        shoeLace17.tipMaterial = "Plastic";
        tipMaterial = shoeLace17.tipMaterial;
        shoeLace17.thickness = 5;
        thickness = shoeLace17.thickness;
        shoeLace17.elastic = false;
        elastic = shoeLace17.elastic;
        shoeLace17.brand = "Merrell";
        brand = shoeLace17.brand;
        shoeLace17.reflective = false;
        reflective = shoeLace17.reflective;
        shoeLace17.pattern = "Striped";
		pattern = shoeLace17.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 18
        ShoeLace shoeLace18 = new ShoeLace();
        shoeLace18.color = "Light Blue";
        color = shoeLace18.color;
        shoeLace18.length = 39;
        length = shoeLace18.length;
        shoeLace18.material = "Leather";
        material = shoeLace18.material;
        shoeLace18.isFlat = false;
        isFlat = shoeLace18.isFlat;
        shoeLace18.tipMaterial = "Metal";
        tipMaterial = shoeLace18.tipMaterial;
        shoeLace18.thickness = 6;
        thickness = shoeLace18.thickness;
        shoeLace18.elastic = true;
        elastic = shoeLace18.elastic;
        shoeLace18.brand = "Salming";
        brand = shoeLace18.brand;
        shoeLace18.reflective = true;
        reflective = shoeLace18.reflective;
        shoeLace18.pattern = "Dotted";
		pattern = shoeLace18.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 19
        ShoeLace shoeLace19 = new ShoeLace();
        shoeLace19.color = "Orange";
        color = shoeLace19.color;
        shoeLace19.length = 41;
        length = shoeLace19.length;
        shoeLace19.material = "Cotton";
        material = shoeLace19.material;
        shoeLace19.isFlat = true;
        isFlat = shoeLace19.isFlat;
        shoeLace19.tipMaterial = "Plastic";
        tipMaterial = shoeLace19.tipMaterial;
        shoeLace19.thickness = 5;
        thickness = shoeLace19.thickness;
        shoeLace19.elastic = false;
        elastic = shoeLace19.elastic;
        shoeLace19.brand = "Vibram";
        brand = shoeLace19.brand;
        shoeLace19.reflective = false;
        reflective = shoeLace19.reflective;
        shoeLace19.pattern = "Solid";
		pattern = shoeLace19.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 20
        ShoeLace shoeLace20 = new ShoeLace();
        shoeLace20.color = "Yellow";
        color = shoeLace20.color;
        shoeLace20.length = 36;
        length = shoeLace20.length;
        shoeLace20.material = "Nylon";
        material = shoeLace20.material;
        shoeLace20.isFlat = false;
        isFlat = shoeLace20.isFlat;
        shoeLace20.tipMaterial = "Metal";
        tipMaterial = shoeLace20.tipMaterial;
        shoeLace20.thickness = 4;
        thickness = shoeLace20.thickness;
        shoeLace20.elastic = true;
        elastic = shoeLace20.elastic;
        shoeLace20.brand = "Columbia";
        brand = shoeLace20.brand;
        shoeLace20.reflective = true;
        reflective = shoeLace20.reflective;
        shoeLace20.pattern = "Striped";
		pattern = shoeLace20.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 21
        ShoeLace shoeLace21 = new ShoeLace();
        shoeLace21.color = "Pink";
        color = shoeLace21.color;
        shoeLace21.length = 46;
        length = shoeLace21.length;
        shoeLace21.material = "Leather";
        material = shoeLace21.material;
        shoeLace21.isFlat = true;
        isFlat = shoeLace21.isFlat;
        shoeLace21.tipMaterial = "Plastic";
        tipMaterial = shoeLace21.tipMaterial;
        shoeLace21.thickness = 5;
        thickness = shoeLace21.thickness;
        shoeLace21.elastic = false;
        elastic = shoeLace21.elastic;
        shoeLace21.brand = "Hoka";
        brand = shoeLace21.brand;
        shoeLace21.reflective = false;
        reflective = shoeLace21.reflective;
        shoeLace21.pattern = "Dotted";
		pattern = shoeLace21.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);
		
		        // ShoeLace 22
        ShoeLace shoeLace22 = new ShoeLace();
        shoeLace22.color = "Dark Green";
        color = shoeLace22.color;
        shoeLace22.length = 40;
        length = shoeLace22.length;
        shoeLace22.material = "Nylon";
        material = shoeLace22.material;
        shoeLace22.isFlat = false;
        isFlat = shoeLace22.isFlat;
        shoeLace22.tipMaterial = "Metal";
        tipMaterial = shoeLace22.tipMaterial;
        shoeLace22.thickness = 6;
        thickness = shoeLace22.thickness;
        shoeLace22.elastic = true;
        elastic = shoeLace22.elastic;
        shoeLace22.brand = "Reebok";
        brand = shoeLace22.brand;
        shoeLace22.reflective = true;
        reflective = shoeLace22.reflective;
        shoeLace22.pattern = "Solid";
		pattern = shoeLace22.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 23
        ShoeLace shoeLace23 = new ShoeLace();
        shoeLace23.color = "Silver";
        color = shoeLace23.color;
        shoeLace23.length = 37;
        length = shoeLace23.length;
        shoeLace23.material = "Cotton";
        material = shoeLace23.material;
        shoeLace23.isFlat = true;
        isFlat = shoeLace23.isFlat;
        shoeLace23.tipMaterial = "Plastic";
        tipMaterial = shoeLace23.tipMaterial;
        shoeLace23.thickness = 5;
        thickness = shoeLace23.thickness;
        shoeLace23.elastic = false;
        elastic = shoeLace23.elastic;
        shoeLace23.brand = "Nike";
        brand = shoeLace23.brand;
        shoeLace23.reflective = false;
        reflective = shoeLace23.reflective;
        shoeLace23.pattern = "Striped";
		pattern = shoeLace23.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 24
        ShoeLace shoeLace24 = new ShoeLace();
        shoeLace24.color = "Gold";
        color = shoeLace24.color;
        shoeLace24.length = 43;
        length = shoeLace24.length;
        shoeLace24.material = "Leather";
        material = shoeLace24.material;
        shoeLace24.isFlat = false;
        isFlat = shoeLace24.isFlat;
        shoeLace24.tipMaterial = "Metal";
        tipMaterial = shoeLace24.tipMaterial;
        shoeLace24.thickness = 6;
        thickness = shoeLace24.thickness;
        shoeLace24.elastic = true;
        elastic = shoeLace24.elastic;
        shoeLace24.brand = "Adidas";
        brand = shoeLace24.brand;
        shoeLace24.reflective = true;
        reflective = shoeLace24.reflective;
        shoeLace24.pattern = "Dotted";
		pattern = shoeLace24.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);

        // ShoeLace 25
        ShoeLace shoeLace25 = new ShoeLace();
        shoeLace25.color = "Turquoise";
        color = shoeLace25.color;
        shoeLace25.length = 45;
        length = shoeLace25.length;
        shoeLace25.material = "Nylon";
        material = shoeLace25.material;
        shoeLace25.isFlat = true;
        isFlat = shoeLace25.isFlat;
        shoeLace25.tipMaterial = "Plastic";
        tipMaterial = shoeLace25.tipMaterial;
        shoeLace25.thickness = 5;
        thickness = shoeLace25.thickness;
        shoeLace25.elastic = false;
        elastic = shoeLace25.elastic;
        shoeLace25.brand = "Puma";
        brand = shoeLace25.brand;
        shoeLace25.reflective = false;
        reflective = shoeLace25.reflective;
        shoeLace25.pattern = "Solid";
		pattern = shoeLace25.pattern;
        System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);
		
		ShoeLace shoeLace = new ShoeLace("Lavender" , 47 , "Cotton" , false , "Metal" , 6 , true , "New Balance" , true , "Striped");
		System.out.println("Color : " + color);
        System.out.println("Length : " + length);
        System.out.println("Material : " + material);
        System.out.println("IS flat : " + isFlat);
        System.out.println("Tip material : " + tipMaterial);
        System.out.println("Thickness :" + thickness);
        System.out.println("Elastic : " + elastic);
        System.out.println("Brand : " + brand);
        System.out.println("Reflective : " + reflective);
        System.out.println("Pattern : " + pattern);
		

		
		


    }
}
		
		

		
		

