public class WonderlaExecutor {
    public static void main(String[] args) {
        /*Wonderla park1 = new Wonderla();
        park1.parkId = 1;
        park1.parkName = "Wonderla Bangalore";
        park1.location = "Bangalore";
        park1.totalRides = 25;
        LazyPoolRide ride1 = new LazyPoolRide();
        ride1.rideId = 101;
        ride1.rideName = "Wave Pool";
        ride1.rideType = "Water";
        park1.lazyPoolRide = ride1;
        park1.displayParkInfo();

        Wonderla park2 = new Wonderla();
        park2.parkId = 2;
        park2.parkName = "Wonderla Kochi";
        park2.location = "Kochi";
        park2.totalRides = 22;
        LazyPoolRide ride2 = new LazyPoolRide();
        ride2.rideId = 102;
        ride2.rideName = "Lazy River";
        ride2.rideType = "Water";
        park2.lazyPoolRide = ride2;
        park2.displayParkInfo();

        Wonderla park3 = new Wonderla();
        park3.parkId = 3;
        park3.parkName = "Wonderla Hyderabad";
        park3.location = "Hyderabad";
        park3.totalRides = 20;
        LazyPoolRide ride3 = new LazyPoolRide();
        ride3.rideId = 103;
        ride3.rideName = "Family Pool";
        ride3.rideType = "Water";
        park3.lazyPoolRide = ride3;
        park3.displayParkInfo();

        Wonderla park4 = new Wonderla();
        park4.parkId = 4;
        park4.parkName = "Wonderla Bangalore-2";
        park4.location = "Bangalore";
        park4.totalRides = 24;
        LazyPoolRide ride4 = new LazyPoolRide();
        ride4.rideId = 104;
        ride4.rideName = "Adventure Pool";
        ride4.rideType = "Water";
        park4.lazyPoolRide = ride4;
        park4.displayParkInfo();

        Wonderla park5 = new Wonderla();
        park5.parkId = 5;
        park5.parkName = "Wonderla Kochi-2";
        park5.location = "Kochi";
        park5.totalRides = 23;
        LazyPoolRide ride5 = new LazyPoolRide();
        ride5.rideId = 105;
        ride5.rideName = "Kids Pool";
        ride5.rideType = "Water";
        park5.lazyPoolRide = ride5;
        park5.displayParkInfo();

        Wonderla park6 = new Wonderla();
        park6.parkId = 6;
        park6.parkName = "Wonderla Hyderabad-2";
        park6.location = "Hyderabad";
        park6.totalRides = 21;
        LazyPoolRide ride6 = new LazyPoolRide();
        ride6.rideId = 106;
        ride6.rideName = "Wave Rider";
        ride6.rideType = "Water";
        park6.lazyPoolRide = ride6;
        park6.displayParkInfo();

        Wonderla park7 = new Wonderla();
        park7.parkId = 7;
        park7.parkName = "Wonderla Bangalore-3";
        park7.location = "Bangalore";
        park7.totalRides = 25;
        LazyPoolRide ride7 = new LazyPoolRide();
        ride7.rideId = 107;
        ride7.rideName = "Lazy Loop";
        ride7.rideType = "Water";
        park7.lazyPoolRide = ride7;
        park7.displayParkInfo();

        Wonderla park8 = new Wonderla();
        park8.parkId = 8;
        park8.parkName = "Wonderla Kochi-3";
        park8.location = "Kochi";
        park8.totalRides = 22;
        LazyPoolRide ride8 = new LazyPoolRide();
        ride8.rideId = 108;
        ride8.rideName = "Wave Rider Extreme";
        ride8.rideType = "Water";
        park8.lazyPoolRide = ride8;
        park8.displayParkInfo();

        Wonderla park9 = new Wonderla();
        park9.parkId = 9;
        park9.parkName = "Wonderla Hyderabad-3";
        park9.location = "Hyderabad";
        park9.totalRides = 20;
        LazyPoolRide ride9 = new LazyPoolRide();
        ride9.rideId = 109;
        ride9.rideName = "Family Fun Pool";
        ride9.rideType = "Water";
        park9.lazyPoolRide = ride9;
        park9.displayParkInfo();

        Wonderla park10 = new Wonderla();
        park10.parkId = 10;
        park10.parkName = "Wonderla Bangalore-4";
        park10.location = "Bangalore";
        park10.totalRides = 26;
        LazyPoolRide ride10 = new LazyPoolRide();
        ride10.rideId = 110;
        ride10.rideName = "Lazy Rapids";
        ride10.rideType = "Water";
        park10.lazyPoolRide = ride10;
        park10.displayParkInfo();

        Wonderla park11 = new Wonderla();
        park11.parkId = 11;
        park11.parkName = "Wonderla Kochi-4";
        park11.location = "Kochi";
        park11.totalRides = 23;
        LazyPoolRide ride11 = new LazyPoolRide();
        ride11.rideId = 111;
        ride11.rideName = "Splash Pool";
        ride11.rideType = "Water";
        park11.lazyPoolRide = ride11;
        park11.displayParkInfo();

        Wonderla park12 = new Wonderla();
        park12.parkId = 12;
        park12.parkName = "Wonderla Hyderabad-4";
        park12.location = "Hyderabad";
        park12.totalRides = 21;
        LazyPoolRide ride12 = new LazyPoolRide();
        ride12.rideId = 112;
        ride12.rideName = "Lazy Stream";
        ride12.rideType = "Water";
        park12.lazyPoolRide = ride12;
        park12.displayParkInfo();

        Wonderla park13 = new Wonderla();
        park13.parkId = 13;
        park13.parkName = "Wonderla Bangalore-5";
        park13.location = "Bangalore";
        park13.totalRides = 24;
        LazyPoolRide ride13 = new LazyPoolRide();
        ride13.rideId = 113;
        ride13.rideName = "Lazy Whirlpool";
        ride13.rideType = "Water";
        park13.lazyPoolRide = ride13;
        park13.displayParkInfo();

        Wonderla park14 = new Wonderla();
        park14.parkId = 14;
        park14.parkName = "Wonderla Kochi-5";
        park14.location = "Kochi";
        park14.totalRides = 22;
        LazyPoolRide ride14 = new LazyPoolRide();
        ride14.rideId = 114;
        ride14.rideName = "Lazy Lagoon";
        ride14.rideType = "Water";
        park14.lazyPoolRide = ride14;
        park14.displayParkInfo();

        Wonderla park15 = new Wonderla();
        park15.parkId = 15;
        park15.parkName = "Wonderla Hyderabad-5";
        park15.location = "Hyderabad";
        park15.totalRides = 20;
        LazyPoolRide ride15 = new LazyPoolRide();
        ride15.rideId = 115;
        ride15.rideName = "Lazy Falls";
        ride15.rideType = "Water";
        park15.lazyPoolRide = ride15;
        park15.displayParkInfo();

        Wonderla park16 = new Wonderla();
        park16.parkId = 16;
        park16.parkName = "Wonderla Bangalore-6";
        park16.location = "Bangalore";
        park16.totalRides = 25;
        LazyPoolRide ride16 = new LazyPoolRide();
        ride16.rideId = 116;
        ride16.rideName = "Lazy Rapids Extreme";
        ride16.rideType = "Water";
        park16.lazyPoolRide = ride16;
        park16.displayParkInfo();

        Wonderla park17 = new Wonderla();
        park17.parkId = 17;
        park17.parkName = "Wonderla Kochi-6";
        park17.location = "Kochi";
        park17.totalRides = 22;
        LazyPoolRide ride17 = new LazyPoolRide();
        ride17.rideId = 117;
        ride17.rideName = "Lazy Bay";
        ride17.rideType = "Water";
        park17.lazyPoolRide = ride17;
        park17.displayParkInfo();

        Wonderla park18 = new Wonderla();
        park18.parkId = 18;
        park18.parkName = "Wonderla Hyderabad-6";
        park18.location = "Hyderabad";
        park18.totalRides = 20;
        LazyPoolRide ride18 = new LazyPoolRide();
        ride18.rideId = 118;
        ride18.rideName = "Lazy Lagoon Extreme";
        ride18.rideType = "Water";
        park18.lazyPoolRide = ride18;
        park18.displayParkInfo();

        Wonderla park19 = new Wonderla();
        park19.parkId = 19;
        park19.parkName = "Wonderla Bangalore-7";
        park19.location = "Bangalore";
        park19.totalRides = 25;
        LazyPoolRide ride19 = new LazyPoolRide();
        ride19.rideId = 119;
        ride19.rideName = "Lazy Falls Extreme";
        ride19.rideType = "Water";
        park19.lazyPoolRide = ride19;
        park19.displayParkInfo();

        Wonderla park20 = new Wonderla();
        park20.parkId = 20;
        park20.parkName = "Wonderla Kochi-7";
        park20.location = "Kochi";
        park20.totalRides = 22;
        LazyPoolRide ride20 = new LazyPoolRide();
        ride20.rideId = 120;
        ride20.rideName = "Lazy Rapids Family";
        ride20.rideType = "Water";
        park20.lazyPoolRide = ride20;
        park20.displayParkInfo();*/

        Wonderla park1 = new Wonderla();
        park1.parkId = 1;
        park1.parkName = "Wonderla Bangalore";
        park1.location = "Bangalore";
        park1.totalRides = 25;
        LazyPoolRide ride1 = new LazyPoolRide();
        ride1.rideId = 101;
        ride1.rideName = "Wave Pool";
        ride1.rideType = "Water";
        park1.lazyPoolRide = ride1;
        park1.displayParkInfo();

        Wonderla park2 = new Wonderla();
        park2.parkId = 2;
        park2.parkName = "Wonderla Kochi";
        park2.location = "Kochi";
        park2.totalRides = 22;
        LazyPoolRide ride2 = new LazyPoolRide();
        ride2.rideId = 102;
        ride2.rideName = "Lazy River";
        ride2.rideType = "Water";
        park2.lazyPoolRide = ride2;
        park2.displayParkInfo();

        Wonderla park3 = new Wonderla();
        park3.parkId = 3;
        park3.parkName = "Wonderla Hyderabad";
        park3.location = "Hyderabad";
        park3.totalRides = 20;
        LazyPoolRide ride3 = new LazyPoolRide();
        ride3.rideId = 103;
        ride3.rideName = "Family Pool";
        ride3.rideType = "Water";
        park3.lazyPoolRide = ride3;
        park3.displayParkInfo();

        Wonderla park4 = new Wonderla();
        park4.parkId = 4;
        park4.parkName = "Wonderla Bangalore-2";
        park4.location = "Bangalore";
        park4.totalRides = 24;
        LazyPoolRide ride4 = new LazyPoolRide();
        ride4.rideId = 104;
        ride4.rideName = "Adventure Pool";
        ride4.rideType = "Water";
        park4.lazyPoolRide = ride4;
        park4.displayParkInfo();

        Wonderla park5 = new Wonderla();
        park5.parkId = 5;
        park5.parkName = "Wonderla Kochi-2";
        park5.location = "Kochi";
        park5.totalRides = 23;
        LazyPoolRide ride5 = new LazyPoolRide();
        ride5.rideId = 105;
        ride5.rideName = "Kids Pool";
        ride5.rideType = "Water";
        park5.lazyPoolRide = ride5;
        park5.displayParkInfo();

        Wonderla park6 = new Wonderla();
        park6.parkId = 6;
        park6.parkName = "Wonderla Hyderabad-2";
        park6.location = "Hyderabad";
        park6.totalRides = 21;
        LazyPoolRide ride6 = new LazyPoolRide();
        ride6.rideId = 106;
        ride6.rideName = "Wave Rider";
        ride6.rideType = "Water";
        park6.lazyPoolRide = ride6;
        park6.displayParkInfo();

        Wonderla park7 = new Wonderla();
        park7.parkId = 7;
        park7.parkName = "Wonderla Bangalore-3";
        park7.location = "Bangalore";
        park7.totalRides = 25;
        LazyPoolRide ride7 = new LazyPoolRide();
        ride7.rideId = 107;
        ride7.rideName = "Lazy Loop";
        ride7.rideType = "Water";
        park7.lazyPoolRide = ride7;
        park7.displayParkInfo();

        Wonderla park8 = new Wonderla();
        park8.parkId = 8;
        park8.parkName = "Wonderla Kochi-3";
        park8.location = "Kochi";
        park8.totalRides = 22;
        LazyPoolRide ride8 = new LazyPoolRide();
        ride8.rideId = 108;
        ride8.rideName = "Wave Rider Extreme";
        ride8.rideType = "Water";
        park8.lazyPoolRide = ride8;
        park8.displayParkInfo();

        Wonderla park9 = new Wonderla();
        park9.parkId = 9;
        park9.parkName = "Wonderla Hyderabad-3";
        park9.location = "Hyderabad";
        park9.totalRides = 20;
        LazyPoolRide ride9 = new LazyPoolRide();
        ride9.rideId = 109;
        ride9.rideName = "Family Fun Pool";
        ride9.rideType = "Water";
        park9.lazyPoolRide = ride9;
        park9.displayParkInfo();

        Wonderla park10 = new Wonderla();
        park10.parkId = 10;
        park10.parkName = "Wonderla Bangalore-4";
        park10.location = "Bangalore";
        park10.totalRides = 26;
        LazyPoolRide ride10 = new LazyPoolRide();
        ride10.rideId = 110;
        ride10.rideName = "Lazy Rapids";
        ride10.rideType = "Water";
        park10.lazyPoolRide = ride10;
        park10.displayParkInfo();

        Wonderla park11 = new Wonderla();
        park11.parkId = 11;
        park11.parkName = "Wonderla Kochi-4";
        park11.location = "Kochi";
        park11.totalRides = 23;
        LazyPoolRide ride11 = new LazyPoolRide();
        ride11.rideId = 111;
        ride11.rideName = "Splash Pool";
        ride11.rideType = "Water";
        park11.lazyPoolRide = ride11;
        park11.displayParkInfo();

        Wonderla park12 = new Wonderla();
        park12.parkId = 12;
        park12.parkName = "Wonderla Hyderabad-4";
        park12.location = "Hyderabad";
        park12.totalRides = 21;
        LazyPoolRide ride12 = new LazyPoolRide();
        ride12.rideId = 112;
        ride12.rideName = "Lazy Stream";
        ride12.rideType = "Water";
        park12.lazyPoolRide = ride12;
        park12.displayParkInfo();

        Wonderla park13 = new Wonderla();
        park13.parkId = 13;
        park13.parkName = "Wonderla Bangalore-5";
        park13.location = "Bangalore";
        park13.totalRides = 24;
        LazyPoolRide ride13 = new LazyPoolRide();
        ride13.rideId = 113;
        ride13.rideName = "Lazy Whirlpool";
        ride13.rideType = "Water";
        park13.lazyPoolRide = ride13;
        park13.displayParkInfo();

        Wonderla park14 = new Wonderla();
        park14.parkId = 14;
        park14.parkName = "Wonderla Kochi-5";
        park14.location = "Kochi";
        park14.totalRides = 22;
        LazyPoolRide ride14 = new LazyPoolRide();
        ride14.rideId = 114;
        ride14.rideName = "Lazy Lagoon";
        ride14.rideType = "Water";
        park14.lazyPoolRide = ride14;
        park14.displayParkInfo();

        Wonderla park15 = new Wonderla();
        park15.parkId = 15;
        park15.parkName = "Wonderla Hyderabad-5";
        park15.location = "Hyderabad";
        park15.totalRides = 20;
        LazyPoolRide ride15 = new LazyPoolRide();
        ride15.rideId = 115;
        ride15.rideName = "Lazy Falls";
        ride15.rideType = "Water";
        park15.lazyPoolRide = ride15;
        park15.displayParkInfo();

        Wonderla park16 = new Wonderla();
        park16.parkId = 16;
        park16.parkName = "Wonderla Bangalore-6";
        park16.location = "Bangalore";
        park16.totalRides = 25;
        LazyPoolRide ride16 = new LazyPoolRide();
        ride16.rideId = 116;
        ride16.rideName = "Lazy Rapids Extreme";
        ride16.rideType = "Water";
        park16.lazyPoolRide = ride16;
        park16.displayParkInfo();

        Wonderla park17 = new Wonderla();
        park17.parkId = 17;
        park17.parkName = "Wonderla Kochi-6";
        park17.location = "Kochi";
        park17.totalRides = 22;
        LazyPoolRide ride17 = new LazyPoolRide();
        ride17.rideId = 117;
        ride17.rideName = "Lazy Bay";
        ride17.rideType = "Water";
        park17.lazyPoolRide = ride17;
        park17.displayParkInfo();

        Wonderla park18 = new Wonderla();
        park18.parkId = 18;
        park18.parkName = "Wonderla Hyderabad-6";
        park18.location = "Hyderabad";
        park18.totalRides = 20;
        LazyPoolRide ride18 = new LazyPoolRide();
        ride18.rideId = 118;
        ride18.rideName = "Lazy Lagoon Extreme";
        ride18.rideType = "Water";
        park18.lazyPoolRide = ride18;
        park18.displayParkInfo();

        Wonderla park19 = new Wonderla();
        park19.parkId = 19;
        park19.parkName = "Wonderla Bangalore-7";
        park19.location = "Bangalore";
        park19.totalRides = 25;
        LazyPoolRide ride19 = new LazyPoolRide();
        ride19.rideId = 119;
        ride19.rideName = "Lazy Falls Extreme";
        ride19.rideType = "Water";
        park19.lazyPoolRide = ride19;
        park19.displayParkInfo();

        Wonderla park20 = new Wonderla();
        park20.parkId = 20;
        park20.parkName = "Wonderla Kochi-7";
        park20.location = "Kochi";
        park20.totalRides = 22;
        LazyPoolRide ride20 = new LazyPoolRide();
        ride20.rideId = 120;
        ride20.rideName = "Lazy Rapids Family";
        ride20.rideType = "Water";
        park20.lazyPoolRide = ride20;
        park20.displayParkInfo();

        
    }
}
