class PeriodicTableExecutor {
    public static void main(String[] tables) {
        PeriodicTable table1 = new PeriodicTable();
        table1.tableId = 1;
        table1.tableName = "Modern Periodic Table";
        table1.discoveryLocation = "Germany";
        table1.totalElements = 118;
        Element element1 = new Element();
        element1.elementId = 101;
        element1.elementName = "Hydrogen";
        element1.elementSymbol = "H";
        table1.element = element1;
        table1.displayTableInfo();

        PeriodicTable table2 = new PeriodicTable();
        table2.tableId = 2;
        table2.tableName = "Modern Periodic Table";
        table2.discoveryLocation = "Germany";
        table2.totalElements = 118;
        Element element2 = new Element();
        element2.elementId = 102;
        element2.elementName = "Helium";
        element2.elementSymbol = "He";
        table2.element = element2;
        table2.displayTableInfo();

        PeriodicTable table3 = new PeriodicTable();
        table3.tableId = 3;
        table3.tableName = "Modern Periodic Table";
        table3.discoveryLocation = "Germany";
        table3.totalElements = 118;
        Element element3 = new Element();
        element3.elementId = 103;
        element3.elementName = "Lithium";
        element3.elementSymbol = "Li";
        table3.element = element3;
        table3.displayTableInfo();

        PeriodicTable table4 = new PeriodicTable();
        table4.tableId = 4;
        table4.tableName = "Modern Periodic Table";
        table4.discoveryLocation = "Germany";
        table4.totalElements = 118;
        Element element4 = new Element();
        element4.elementId = 104;
        element4.elementName = "Beryllium";
        element4.elementSymbol = "Be";
        table4.element = element4;
        table4.displayTableInfo();

        PeriodicTable table5 = new PeriodicTable();
        table5.tableId = 5;
        table5.tableName = "Modern Periodic Table";
        table5.discoveryLocation = "Germany";
        table5.totalElements = 118;
        Element element5 = new Element();
        element5.elementId = 105;
        element5.elementName = "Boron";
        element5.elementSymbol = "B";
        table5.element = element5;
        table5.displayTableInfo();

        PeriodicTable table6 = new PeriodicTable();
        table6.tableId = 6;
        table6.tableName = "Modern Periodic Table";
        table6.discoveryLocation = "Germany";
        table6.totalElements = 118;
        Element element6 = new Element();
        element6.elementId = 106;
        element6.elementName = "Carbon";
        element6.elementSymbol = "C";
        table6.element = element6;
        table6.displayTableInfo();

        PeriodicTable table7 = new PeriodicTable();
        table7.tableId = 7;
        table7.tableName = "Modern Periodic Table";
        table7.discoveryLocation = "Germany";
        table7.totalElements = 118;
        Element element7 = new Element();
        element7.elementId = 107;
        element7.elementName = "Nitrogen";
        element7.elementSymbol = "N";
        table7.element = element7;
        table7.displayTableInfo();

        PeriodicTable table8 = new PeriodicTable();
        table8.tableId = 8;
        table8.tableName = "Modern Periodic Table";
        table8.discoveryLocation = "Germany";
        table8.totalElements = 118;
        Element element8 = new Element();
        element8.elementId = 108;
        element8.elementName = "Oxygen";
        element8.elementSymbol = "O";
        table8.element = element8;
        table8.displayTableInfo();

        PeriodicTable table9 = new PeriodicTable();
        table9.tableId = 9;
        table9.tableName = "Modern Periodic Table";
        table9.discoveryLocation = "Germany";
        table9.totalElements = 118;
        Element element9 = new Element();
        element9.elementId = 109;
        element9.elementName = "Fluorine";
        element9.elementSymbol = "F";
        table9.element = element9;
        table9.displayTableInfo();

        PeriodicTable table10 = new PeriodicTable();
        table10.tableId = 10;
        table10.tableName = "Modern Periodic Table";
        table10.discoveryLocation = "Germany";
        table10.totalElements = 118;
        Element element10 = new Element();
        element10.elementId = 110;
        element10.elementName = "Neon";
        element10.elementSymbol = "Ne";
        table10.element = element10;
        table10.displayTableInfo();

        PeriodicTable table11 = new PeriodicTable();
        table11.tableId = 11;
        table11.tableName = "Modern Periodic Table";
        table11.discoveryLocation = "Germany";
        table11.totalElements = 118;
        Element element11 = new Element();
        element11.elementId = 111;
        element11.elementName = "Sodium";
        element11.elementSymbol = "Na";
        table11.element = element11;
        table11.displayTableInfo();

        PeriodicTable table12 = new PeriodicTable();
        table12.tableId = 12;
        table12.tableName = "Modern Periodic Table";
        table12.discoveryLocation = "Germany";
        table12.totalElements = 118;
        Element element12 = new Element();
        element12.elementId = 112;
        element12.elementName = "Magnesium";
        element12.elementSymbol = "Mg";
        table12.element = element12;
        table12.displayTableInfo();

        PeriodicTable table13 = new PeriodicTable();
        table13.tableId = 13;
        table13.tableName = "Modern Periodic Table";
        table13.discoveryLocation = "Germany";
        table13.totalElements = 118;
        Element element13 = new Element();
        element13.elementId = 113;
        element13.elementName = "Aluminium";
        element13.elementSymbol = "Al";
        table13.element = element13;
        table13.displayTableInfo();

        PeriodicTable table14 = new PeriodicTable();
        table14.tableId = 14;
        table14.tableName = "Modern Periodic Table";
        table14.discoveryLocation = "Germany";
        table14.totalElements = 118;
        Element element14 = new Element();
        element14.elementId = 114;
        element14.elementName = "Silicon";
        element14.elementSymbol = "Si";
        table14.element = element14;
        table14.displayTableInfo();

        PeriodicTable table15 = new PeriodicTable();
        table15.tableId = 15;
        table15.tableName = "Modern Periodic Table";
        table15.discoveryLocation = "Germany";
        table15.totalElements = 118;
        Element element15 = new Element();
        element15.elementId = 115;
        element15.elementName = "Phosphorus";
        element15.elementSymbol = "P";
        table15.element = element15;
        table15.displayTableInfo();

        PeriodicTable table16 = new PeriodicTable();
        table16.tableId = 16;
        table16.tableName = "Modern Periodic Table";
        table16.discoveryLocation = "Germany";
        table16.totalElements = 118;
        Element element16 = new Element();
        element16.elementId = 116;
        element16.elementName = "Sulfur";
        element16.elementSymbol = "S";
        table16.element = element16;
        table16.displayTableInfo();

        PeriodicTable table17 = new PeriodicTable();
        table17.tableId = 17;
        table17.tableName = "Modern Periodic Table";
        table17.discoveryLocation = "Germany";
        table17.totalElements = 118;
        Element element17 = new Element();
        element17.elementId = 117;
        element17.elementName = "Chlorine";
        element17.elementSymbol = "Cl";
        table17.element = element17;
        table17.displayTableInfo();

        PeriodicTable table18 = new PeriodicTable();
        table18.tableId = 18;
        table18.tableName = "Modern Periodic Table";
        table18.discoveryLocation = "Germany";
        table18.totalElements = 118;
        Element element18 = new Element();
        element18.elementId = 118;
        element18.elementName = "Argon";
        element18.elementSymbol = "Ar";
        table18.element = element18;
        table18.displayTableInfo();

        PeriodicTable table19 = new PeriodicTable();
        table19.tableId = 19;
        table19.tableName = "Modern Periodic Table";
        table19.discoveryLocation = "Germany";
        table19.totalElements = 118;
        Element element19 = new Element();
        element19.elementId = 119;
        element19.elementName = "Potassium";
        element19.elementSymbol = "K";
        table19.element = element19;
        table19.displayTableInfo();

        PeriodicTable table20 = new PeriodicTable();
        table20.tableId = 20;
        table20.tableName = "Modern Periodic Table";
        table20.discoveryLocation = "Germany";
        table20.totalElements = 118;
        Element element20 = new Element();
        element20.elementId = 120;
        element20.elementName = "Calcium";
        element20.elementSymbol = "Ca";
        table20.element = element20;
        table20.displayTableInfo();
    }
}